"""Run same-ranked-list curated-vs-dynamic GSEA comparison."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from npathway.pipeline import compare_curated_vs_dynamic_gsea


def _parse_focus_genes(value: str) -> list[str]:
    return [part.strip() for part in str(value).split(",") if part.strip()]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ranked-genes",
        required=True,
        help="Path to a ranked gene table with at least gene and score columns.",
    )
    parser.add_argument(
        "--dynamic-gmt",
        required=True,
        help="Path to the dynamic-program GMT generated by nPathway.",
    )
    parser.add_argument(
        "--curated-gmt",
        required=True,
        help="Path to the curated pathway GMT used for the comparison arm.",
    )
    parser.add_argument(
        "--gene-col",
        default="gene",
        help="Gene column name in --ranked-genes.",
    )
    parser.add_argument(
        "--score-col",
        default="score",
        help="Score column name in --ranked-genes.",
    )
    parser.add_argument(
        "--sep",
        default=None,
        help="Delimiter override for --ranked-genes (default: auto infer).",
    )
    parser.add_argument(
        "--focus-genes",
        default="",
        help="Comma-separated genes to track in dynamic versus curated outputs.",
    )
    parser.add_argument(
        "--gsea-n-perm",
        type=int,
        default=1000,
        help="Number of permutations for preranked GSEA.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed.")
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory (default: <dynamic-gmt dir>/comparison).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    """CLI entrypoint."""
    args = parse_args(argv)
    if args.gsea_n_perm < 1:
        raise ValueError("--gsea-n-perm must be >= 1.")

    output_dir = (
        Path(args.output_dir)
        if args.output_dir is not None
        else Path(args.dynamic_gmt).resolve().parent / "comparison"
    )
    result = compare_curated_vs_dynamic_gsea(
        ranked_genes_path=args.ranked_genes,
        dynamic_gmt_path=args.dynamic_gmt,
        curated_gmt_path=args.curated_gmt,
        output_dir=output_dir,
        gene_col=args.gene_col,
        score_col=args.score_col,
        sep=args.sep,
        n_perm=args.gsea_n_perm,
        seed=args.seed,
        focus_genes=_parse_focus_genes(args.focus_genes),
    )
    manifest = {
        "ranked_genes": str(args.ranked_genes),
        "dynamic_gmt": str(args.dynamic_gmt),
        "curated_gmt": str(args.curated_gmt),
        "gene_col": str(args.gene_col),
        "score_col": str(args.score_col),
        "focus_genes": _parse_focus_genes(args.focus_genes),
        "result": result.__dict__,
    }
    (output_dir / "comparison_cli_manifest.json").write_text(
        json.dumps(manifest, indent=2),
        encoding="utf-8",
    )

    print("nPathway comparison mode completed.")
    print(f"- output_dir: {result.output_dir}")
    print(f"- n_ranked_genes: {result.n_ranked_genes}")
    print(f"- n_dynamic_programs: {result.n_dynamic_programs}")
    print(f"- n_curated_sets: {result.n_curated_sets}")
    print(f"- anchor_program: {result.anchor_program}")
    print(f"- anchor_reference: {result.anchor_reference}")
    print(f"- anchor_jaccard: {result.anchor_jaccard}")
    print(f"- n_focus_genes_in_anchor_program: {result.n_focus_genes_in_anchor_program}")
    print(f"- n_focus_genes_in_curated_sets: {result.n_focus_genes_in_curated_sets}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        print(
            "Hint: run `npathway compare ...` with a full ranked gene table, an nPathway dynamic GMT, and a curated GMT.",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc
